name: Publish to Maven Central
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
      - name: Publish to Maven Central
        uses: "marc-kgp/github-maven-action@v1.0"
        with:
          pom: "build/publications/mavenJava/pom-default.xml"
        env:
          GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
